name: intl_utils
description: intl_utils is a dart library that generates Dart localization code from ARB file. Generated code relies on Intl library.
version: 2.7.1
homepage: https://github.com/localizely/intl_utils

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  analyzer: ^5.2.0
  archive: ^3.3.2
  args: ^2.3.1
  dart_style: ^2.2.4
  http: ^0.13.5
  intl: ^0.17.0
  path: ^1.8.2
  petitparser: '>=5.1.0'
  yaml: ^3.1.1

dev_dependencies:
  build_runner: ^2.0.6
  lints: ^1.0.0
  mockito: ^5.0.12
  test: ^1.16.0
